[toolchain]

[features]
seeds = false
skip-lint = false

[programs.testnet]
mines = "5ViMkjJFgjUD9tuouTpjZ3m86jyGH8iB6h3r4Dxa4BCe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.testnet.x1.xyz"
wallet = "keys/deployer-testnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
