// GENERATED FILE — do not edit by hand.
// Produced by scripts/generate-cards.ts from the authoritative, fully-balanced (v3)
// card data exported by the Python reference simulator (sim/results/FINAL_BALANCED_CARDS_v3.json).
// Regenerate with: npx tsx scripts/generate-cards.ts
import type { Card } from "./types";

export const CARDS: Card[] = [
  {
    id: "MIN-01",
    name: "Rig Rookie",
    type: "UNIT",
    faction: "MINERS",
    cost: 1,
    atk: 1,
    hp: 2,
    rarity: "COMMON",
    keywords: [],
    onPlay: null,
    passive: null,
    onDeath: null,
    text: "Brak zdolności.",
    copies: 2,
  },
  {
    id: "MIN-02",
    name: "Hash Apprentice",
    type: "UNIT",
    faction: "MINERS",
    cost: 1,
    atk: 1,
    hp: 1,
    rarity: "COMMON",
    keywords: ["YIELD_1"],
    onPlay: null,
    passive: null,
    onDeath: null,
    text: "Yield 1: dopóki ta jednostka żyje, jej kontroler otrzymuje +1 Gas w Fazie Gas (łączny limit Gas/rundę: 7).",
    copies: 2,
  },
  {
    id: "MIN-03",
    name: "Dusty Rig",
    type: "UNIT",
    faction: "MINERS",
    cost: 2,
    atk: 1,
    hp: 3,
    rarity: "COMMON",
    keywords: ["YIELD_1"],
    onPlay: null,
    passive: null,
    onDeath: null,
    text: "Yield 1.",
    copies: 2,
  },
  {
    id: "MIN-04",
    name: "Power Surge",
    type: "ACTION",
    faction: "MINERS",
    cost: 2,
    atk: null,
    hp: null,
    rarity: "UNCOMMON",
    keywords: [],
    onPlay: {"op":"GAIN_GAS","amount":2},
    passive: null,
    onDeath: null,
    text: "Zyskaj 2 Gas w tej rundzie (do limitu 8).",
    copies: 2,
  },
  {
    id: "MIN-05",
    name: "Cooling Fan Tech",
    type: "UNIT",
    faction: "MINERS",
    cost: 2,
    atk: 2,
    hp: 3,
    rarity: "COMMON",
    keywords: [],
    onPlay: null,
    passive: null,
    onDeath: null,
    text: "Brak zdolności.",
    copies: 2,
  },
  {
    id: "MIN-06",
    name: "Mining Pool",
    type: "STRUCTURE",
    faction: "MINERS",
    cost: 3,
    atk: null,
    hp: 3,
    rarity: "UNCOMMON",
    keywords: [],
    onPlay: null,
    passive: {"op":"GAIN_GAS_PASSIVE_STRUCTURE","amount":1},
    onDeath: null,
    text: "Na początku każdej Fazy Gas kontroler otrzymuje +1 Gas (do limitu 8), dopóki ta struktura żyje.",
    copies: 2,
  },
  {
    id: "MIN-07",
    name: "Overclocked Rig",
    type: "UNIT",
    faction: "MINERS",
    cost: 3,
    atk: 2,
    hp: 4,
    rarity: "RARE",
    keywords: ["YIELD_1"],
    onPlay: null,
    passive: null,
    onDeath: null,
    text: "Yield 2.",
    copies: 2,
  },
  {
    id: "MIN-08",
    name: "Salvage Bot",
    type: "UNIT",
    faction: "MINERS",
    cost: 3,
    atk: 3,
    hp: 2,
    rarity: "COMMON",
    keywords: [],
    onPlay: null,
    passive: null,
    onDeath: {"op":"DRAW","amount":1},
    text: "Po zniszczeniu: dobierz 1 kartę.",
    copies: 2,
  },
  {
    id: "MIN-09",
    name: "ASIC Titan",
    type: "UNIT",
    faction: "MINERS",
    cost: 4,
    atk: 3,
    hp: 5,
    rarity: "RARE",
    keywords: ["YIELD_1"],
    onPlay: null,
    passive: null,
    onDeath: null,
    text: "Yield 1.",
    copies: 1,
  },
  {
    id: "MIN-10",
    name: "Halving Event",
    type: "ACTION",
    faction: "MINERS",
    cost: 4,
    atk: null,
    hp: null,
    rarity: "EPIC",
    keywords: [],
    onPlay: {"op":"DRAW_AND_GAS","draw":2,"gas":1},
    passive: null,
    onDeath: null,
    text: "Dobierz 2 karty. Zyskaj 1 Gas w tej rundzie.",
    copies: 1,
  },
  {
    id: "MIN-11",
    name: "Liquidity Vein",
    type: "UNIT",
    faction: "MINERS",
    cost: 5,
    atk: 3,
    hp: 6,
    rarity: "RARE",
    keywords: [],
    onPlay: null,
    passive: {"op":"YIELD_AURA","amount":1},
    onDeath: null,
    text: "Inne własne jednostki Miners na tym węźle mają Yield +1 (nie kumuluje się z ich własnym Yield, dodaje osobno).",
    copies: 1,
  },
  {
    id: "MIN-12",
    name: "Genesis Block Colossus",
    type: "UNIT",
    faction: "MINERS",
    cost: 6,
    atk: 5,
    hp: 7,
    rarity: "LEGENDARY",
    keywords: ["YIELD_2"],
    onPlay: {"op":"DRAW","amount":1},
    passive: null,
    onDeath: null,
    text: "Yield 3. Po zagraniu: dobierz 1 kartę.",
    copies: 1,
  },
  {
    id: "DEG-01",
    name: "Shitcoin Shiller",
    type: "UNIT",
    faction: "DEGENS",
    cost: 1,
    atk: 2,
    hp: 1,
    rarity: "COMMON",
    keywords: [],
    onPlay: null,
    passive: null,
    onDeath: null,
    text: "Brak zdolności.",
    copies: 2,
  },
  {
    id: "DEG-02",
    name: "Leverage Ape",
    type: "UNIT",
    faction: "DEGENS",
    cost: 1,
    atk: 1,
    hp: 1,
    rarity: "COMMON",
    keywords: ["PUMP"],
    onPlay: null,
    passive: null,
    onDeath: null,
    text: "Pump: pierwszy raz, gdy ta jednostka zadaje obrażenia w walce, zyskuje trwale +1 ATK.",
    copies: 2,
  },
  {
    id: "DEG-03",
    name: "FOMO Trader",
    type: "UNIT",
    faction: "DEGENS",
    cost: 2,
    atk: 3,
    hp: 1,
    rarity: "COMMON",
    keywords: [],
    onPlay: null,
    passive: null,
    onDeath: null,
    text: "Brak zdolności. Ginie od każdego trafienia — wysokie ryzyko, wysoki Hashpower/koszt.",
    copies: 2,
  },
  {
    id: "DEG-04",
    name: "Pump Signal",
    type: "ACTION",
    faction: "DEGENS",
    cost: 2,
    atk: null,
    hp: null,
    rarity: "UNCOMMON",
    keywords: [],
    onPlay: {"op":"BUFF_ATK","amount":2,"target":"own_best_at_node"},
    passive: null,
    onDeath: null,
    text: "Wybrana własna jednostka na wskazanym węźle zyskuje trwale +2 ATK.",
    copies: 2,
  },
  {
    id: "DEG-05",
    name: "Rug Puller",
    type: "UNIT",
    faction: "DEGENS",
    cost: 2,
    atk: 2,
    hp: 2,
    rarity: "UNCOMMON",
    keywords: [],
    onPlay: {"op":"POISON","amount":1,"target":"enemy_best_at_node"},
    passive: null,
    onDeath: null,
    text: "Po zagraniu: nałóż Zatrucie 1 na wrogą jednostkę na tym węźle.",
    copies: 2,
  },
  {
    id: "DEG-06",
    name: "Degenerate Gambler",
    type: "UNIT",
    faction: "DEGENS",
    cost: 3,
    atk: 3,
    hp: 2,
    rarity: "RARE",
    keywords: ["PUMP"],
    onPlay: null,
    passive: null,
    onDeath: null,
    text: "Pump.",
    copies: 2,
  },
  {
    id: "DEG-07",
    name: "All-In Bet",
    type: "ACTION",
    faction: "DEGENS",
    cost: 3,
    atk: null,
    hp: null,
    rarity: "RARE",
    keywords: [],
    onPlay: {"op":"BURN","amount":3,"target":"enemy_best_at_node"},
    passive: null,
    onDeath: null,
    text: "Zadaj 3 obrażenia wrogiej jednostce na wskazanym węźle. Jeśli ją zniszczysz, zyskaj 2 Gas.",
    copies: 2,
  },
  {
    id: "DEG-08",
    name: "Moonshot Maxi",
    type: "UNIT",
    faction: "DEGENS",
    cost: 3,
    atk: 3,
    hp: 3,
    rarity: "COMMON",
    keywords: ["RUSH"],
    onPlay: null,
    passive: null,
    onDeath: null,
    text: "Rush.",
    copies: 2,
  },
  {
    id: "DEG-09",
    name: "100x Leverage",
    type: "UNIT",
    faction: "DEGENS",
    cost: 4,
    atk: 6,
    hp: 2,
    rarity: "EPIC",
    keywords: ["PUMP"],
    onPlay: null,
    passive: null,
    onDeath: null,
    text: "Pump. Bardzo krucha — ginie od niemal każdej odpowiedzi.",
    copies: 1,
  },
  {
    id: "DEG-10",
    name: "Liquidation Cascade",
    type: "ACTION",
    faction: "DEGENS",
    cost: 4,
    atk: null,
    hp: null,
    rarity: "RARE",
    keywords: [],
    onPlay: {"op":"DAMAGE_ALL_ENEMIES_AT_NODE","amount":2},
    passive: null,
    onDeath: null,
    text: "Zadaj 2 obrażenia wszystkim wrogim jednostkom na wskazanym węźle.",
    copies: 1,
  },
  {
    id: "DEG-11",
    name: "Diamond-Handed Degen",
    type: "UNIT",
    faction: "DEGENS",
    cost: 5,
    atk: 5,
    hp: 4,
    rarity: "RARE",
    keywords: ["RUSH"],
    onPlay: null,
    passive: null,
    onDeath: null,
    text: "Rush.",
    copies: 1,
  },
  {
    id: "DEG-12",
    name: "Ape God",
    type: "UNIT",
    faction: "DEGENS",
    cost: 6,
    atk: 7,
    hp: 3,
    rarity: "LEGENDARY",
    keywords: ["PUMP","RUSH"],
    onPlay: {"op":"FREEZE","target":"enemy_best_at_node"},
    passive: null,
    onDeath: null,
    text: "Pump. Rush. Po zagraniu: zamróź wrogą jednostkę na tym węźle.",
    copies: 1,
  },
  {
    id: "BLD-01",
    name: "Junior Dev",
    type: "UNIT",
    faction: "BUILDERS",
    cost: 1,
    atk: 1,
    hp: 2,
    rarity: "COMMON",
    keywords: [],
    onPlay: null,
    passive: null,
    onDeath: null,
    text: "Brak zdolności.",
    copies: 2,
  },
  {
    id: "BLD-02",
    name: "Protocol Architect",
    type: "UNIT",
    faction: "BUILDERS",
    cost: 1,
    atk: 1,
    hp: 1,
    rarity: "COMMON",
    keywords: ["SYNERGY"],
    onPlay: {"op":"SHIELD_IF_SYNERGY","min_synergy":1},
    passive: null,
    onDeath: null,
    text: "Synergy: po zagraniu, jeśli masz co najmniej 1 inną jednostkę Builders na tym węźle, ta jednostka zyskuje Tarczę.",
    copies: 2,
  },
  {
    id: "BLD-03",
    name: "Smart Contract",
    type: "STRUCTURE",
    faction: "BUILDERS",
    cost: 2,
    atk: null,
    hp: 4,
    rarity: "UNCOMMON",
    keywords: [],
    onPlay: null,
    passive: {"op":"AURA_ATK_FACTION","faction":"BUILDERS","amount":2},
    onDeath: null,
    text: "Dopóki żyje: własne jednostki Builders na tym węźle mają +1 ATK.",
    copies: 2,
  },
  {
    id: "BLD-04",
    name: "Modular Stack",
    type: "UNIT",
    faction: "BUILDERS",
    cost: 2,
    atk: 1,
    hp: 4,
    rarity: "COMMON",
    keywords: [],
    onPlay: null,
    passive: null,
    onDeath: null,
    text: "Brak zdolności.",
    copies: 2,
  },
  {
    id: "BLD-05",
    name: "Composability Engine",
    type: "ACTION",
    faction: "BUILDERS",
    cost: 2,
    atk: null,
    hp: null,
    rarity: "UNCOMMON",
    keywords: ["SYNERGY"],
    onPlay: {"op":"BURN_SYNERGY","base":2,"target":"enemy_best_at_node"},
    passive: null,
    onDeath: null,
    text: "Synergy: zadaj obrażenia wrogiej jednostce na wskazanym węźle równe liczbie Twoich innych jednostek Builders tam (min. 1).",
    copies: 2,
  },
  {
    id: "BLD-06",
    name: "Cross-Chain Bridge",
    type: "UNIT",
    faction: "BUILDERS",
    cost: 3,
    atk: 2,
    hp: 4,
    rarity: "RARE",
    keywords: ["SYNERGY"],
    onPlay: {"op":"DRAW_SYNERGY","per":2,"max_draw":2},
    passive: null,
    onDeath: null,
    text: "Synergy: po zagraniu dobierz kartę za każde 2 inne własne jednostki Builders na tym węźle (maks. 2).",
    copies: 2,
  },
  {
    id: "BLD-07",
    name: "Refactor",
    type: "ACTION",
    faction: "BUILDERS",
    cost: 3,
    atk: null,
    hp: null,
    rarity: "COMMON",
    keywords: [],
    onPlay: {"op":"DRAW_AND_GAS","draw":1,"gas":1},
    passive: null,
    onDeath: null,
    text: "Zniszcz własną jednostkę na wskazanym węźle. Zyskaj 2 Gas i dobierz 1 kartę.",
    copies: 2,
  },
  {
    id: "BLD-08",
    name: "Upgrade Node",
    type: "UNIT",
    faction: "BUILDERS",
    cost: 3,
    atk: 3,
    hp: 4,
    rarity: "COMMON",
    keywords: [],
    onPlay: null,
    passive: null,
    onDeath: null,
    text: "Brak zdolności.",
    copies: 2,
  },
  {
    id: "BLD-09",
    name: "DAO Council",
    type: "UNIT",
    faction: "BUILDERS",
    cost: 4,
    atk: 3,
    hp: 5,
    rarity: "RARE",
    keywords: ["SYNERGY"],
    onPlay: null,
    passive: {"op":"SYNERGY_ATK_SELF","amount":2},
    onDeath: null,
    text: "Synergy: ta jednostka ma +1 ATK za każdą inną własną jednostkę Builders na tym węźle.",
    copies: 1,
  },
  {
    id: "BLD-10",
    name: "Mainnet Launch",
    type: "ACTION",
    faction: "BUILDERS",
    cost: 4,
    atk: null,
    hp: null,
    rarity: "EPIC",
    keywords: [],
    onPlay: {"op":"BUFF_ATK_HP_ALL_OWN_FACTION_AT_NODE","atk":3,"hp":3},
    passive: null,
    onDeath: null,
    text: "Wszystkie własne jednostki Builders na wskazanym węźle zyskują trwale +2/+2.",
    copies: 1,
  },
  {
    id: "BLD-11",
    name: "Infinite Scalability",
    type: "UNIT",
    faction: "BUILDERS",
    cost: 5,
    atk: 4,
    hp: 6,
    rarity: "RARE",
    keywords: ["SYNERGY"],
    onPlay: {"op":"RETURN_RANDOM_FROM_GRAVEYARD","min_synergy":2},
    passive: null,
    onDeath: null,
    text: "Synergy: jeśli masz co najmniej 2 inne jednostki Builders na tym węźle, przywróć losową kartę Builders z cmentarza do ręki.",
    copies: 1,
  },
  {
    id: "BLD-12",
    name: "The Everything Chain",
    type: "UNIT",
    faction: "BUILDERS",
    cost: 6,
    atk: 4,
    hp: 6,
    rarity: "LEGENDARY",
    keywords: [],
    onPlay: {"op":"DRAW","amount":1},
    passive: {"op":"AURA_ATK_FACTION","faction":"BUILDERS","amount":2},
    onDeath: null,
    text: "Dopóki żyje: inne własne jednostki Builders na tym węźle mają +1 ATK. Po zagraniu: dobierz 1 kartę.",
    copies: 1,
  },
  {
    id: "VAL-01",
    name: "Node Operator",
    type: "UNIT",
    faction: "VALIDATORS",
    cost: 1,
    atk: 2,
    hp: 2,
    rarity: "COMMON",
    keywords: [],
    onPlay: null,
    passive: null,
    onDeath: null,
    text: "Brak zdolności.",
    copies: 2,
  },
  {
    id: "VAL-02",
    name: "Slashing Watchdog",
    type: "UNIT",
    faction: "VALIDATORS",
    cost: 1,
    atk: 1,
    hp: 1,
    rarity: "COMMON",
    keywords: ["GUARD"],
    onPlay: null,
    passive: null,
    onDeath: null,
    text: "Guard.",
    copies: 2,
  },
  {
    id: "VAL-03",
    name: "Consensus Guard",
    type: "UNIT",
    faction: "VALIDATORS",
    cost: 2,
    atk: 2,
    hp: 3,
    rarity: "UNCOMMON",
    keywords: ["GUARD","FORTIFY"],
    onPlay: null,
    passive: null,
    onDeath: null,
    text: "Guard. Fortify: na początku rundy, jeśli nie atakowała w poprzedniej rundzie, zyskuje Tarczę.",
    copies: 2,
  },
  {
    id: "VAL-04",
    name: "Firewall Patch",
    type: "ACTION",
    faction: "VALIDATORS",
    cost: 2,
    atk: null,
    hp: null,
    rarity: "UNCOMMON",
    keywords: [],
    onPlay: {"op":"SHIELD_AND_BUFF_HP","hp":2,"target":"own_best_at_node"},
    passive: null,
    onDeath: null,
    text: "Wybrana własna jednostka na wskazanym węźle zyskuje Tarczę i trwale +0/+2.",
    copies: 2,
  },
  {
    id: "VAL-05",
    name: "Audit Report",
    type: "ACTION",
    faction: "VALIDATORS",
    cost: 2,
    atk: null,
    hp: null,
    rarity: "COMMON",
    keywords: [],
    onPlay: {"op":"OVERLOAD","amount":2,"target":"enemy_best_at_node"},
    passive: null,
    onDeath: null,
    text: "Nałóż Przeciążenie 2 na wrogą jednostkę na wskazanym węźle.",
    copies: 2,
  },
  {
    id: "VAL-06",
    name: "Bastion Validator",
    type: "UNIT",
    faction: "VALIDATORS",
    cost: 3,
    atk: 3,
    hp: 5,
    rarity: "RARE",
    keywords: ["GUARD","FORTIFY"],
    onPlay: null,
    passive: null,
    onDeath: null,
    text: "Guard. Fortify.",
    copies: 2,
  },
  {
    id: "VAL-07",
    name: "Circuit Breaker",
    type: "ACTION",
    faction: "VALIDATORS",
    cost: 3,
    atk: null,
    hp: null,
    rarity: "RARE",
    keywords: [],
    onPlay: {"op":"DESTROY_IF","condition":"atk_lte","value":4,"target":"enemy_best_at_node"},
    passive: null,
    onDeath: null,
    text: "Zniszcz wrogą jednostkę o ATK 3 lub mniejszym na wskazanym węźle.",
    copies: 2,
  },
  {
    id: "VAL-08",
    name: "Redundant Array",
    type: "UNIT",
    faction: "VALIDATORS",
    cost: 3,
    atk: 3,
    hp: 5,
    rarity: "COMMON",
    keywords: [],
    onPlay: null,
    passive: null,
    onDeath: null,
    text: "Brak zdolności.",
    copies: 2,
  },
  {
    id: "VAL-09",
    name: "Immutable Ledger",
    type: "STRUCTURE",
    faction: "VALIDATORS",
    cost: 3,
    atk: null,
    hp: 6,
    rarity: "RARE",
    keywords: [],
    onPlay: null,
    passive: {"op":"NO_RETALIATION_DAMAGE_OWN_AT_NODE"},
    onDeath: null,
    text: "Dopóki żyje: własne jednostki na tym węźle nie otrzymują obrażeń z retaliacji (nadal mogą ginąć od obrażeń bezpośrednich z ataku i efektów).",
    copies: 1,
  },
  {
    id: "VAL-10",
    name: "Emergency Fork",
    type: "ACTION",
    faction: "VALIDATORS",
    cost: 4,
    atk: null,
    hp: null,
    rarity: "EPIC",
    keywords: [],
    onPlay: {"op":"DESTROY_AND_SHIELD","target":"enemy_best_at_node","shield_target":"own_best_at_node"},
    passive: null,
    onDeath: null,
    text: "Zniszcz wrogą jednostkę na wskazanym węźle. Wybrana własna jednostka na tym samym węźle zyskuje Tarczę.",
    copies: 1,
  },
  {
    id: "VAL-11",
    name: "Fortress Chain",
    type: "UNIT",
    faction: "VALIDATORS",
    cost: 5,
    atk: 4,
    hp: 8,
    rarity: "RARE",
    keywords: ["GUARD","FORTIFY"],
    onPlay: null,
    passive: null,
    onDeath: null,
    text: "Guard. Fortify.",
    copies: 1,
  },
  {
    id: "VAL-12",
    name: "Sentinel Prime",
    type: "UNIT",
    faction: "VALIDATORS",
    cost: 6,
    atk: 5,
    hp: 9,
    rarity: "LEGENDARY",
    keywords: ["GUARD","FORTIFY"],
    onPlay: {"op":"GRANT_SHIELD_ALL_OWN_AT_NODE"},
    passive: null,
    onDeath: null,
    text: "Guard. Fortify. Po zagraniu: wszystkie własne jednostki na tym węźle zyskują Tarczę.",
    copies: 1,
  },
  {
    id: "NEU-01",
    name: "Faucet Drip",
    type: "UNIT",
    faction: "NEUTRAL",
    cost: 1,
    atk: 1,
    hp: 1,
    rarity: "BASIC",
    keywords: [],
    onPlay: null,
    passive: null,
    onDeath: null,
    text: "Brak zdolności.",
    copies: 2,
  },
  {
    id: "NEU-02",
    name: "Community Manager",
    type: "UNIT",
    faction: "NEUTRAL",
    cost: 1,
    atk: 0,
    hp: 3,
    rarity: "COMMON",
    keywords: ["GUARD"],
    onPlay: null,
    passive: null,
    onDeath: null,
    text: "Guard.",
    copies: 2,
  },
  {
    id: "NEU-03",
    name: "Airdrop Hunter",
    type: "UNIT",
    faction: "NEUTRAL",
    cost: 2,
    atk: 2,
    hp: 2,
    rarity: "COMMON",
    keywords: [],
    onPlay: null,
    passive: null,
    onDeath: null,
    text: "Brak zdolności.",
    copies: 2,
  },
  {
    id: "NEU-04",
    name: "Gas Rebate",
    type: "ACTION",
    faction: "NEUTRAL",
    cost: 1,
    atk: null,
    hp: null,
    rarity: "COMMON",
    keywords: [],
    onPlay: {"op":"GAIN_GAS","amount":1},
    passive: null,
    onDeath: null,
    text: "Zyskaj 1 Gas w tej rundzie.",
    copies: 2,
  },
  {
    id: "NEU-05",
    name: "Market Maker",
    type: "UNIT",
    faction: "NEUTRAL",
    cost: 2,
    atk: 2,
    hp: 3,
    rarity: "UNCOMMON",
    keywords: [],
    onPlay: null,
    passive: null,
    onDeath: null,
    text: "Brak zdolności.",
    copies: 2,
  },
  {
    id: "NEU-06",
    name: "Meme Lord",
    type: "UNIT",
    faction: "NEUTRAL",
    cost: 3,
    atk: 3,
    hp: 3,
    rarity: "COMMON",
    keywords: [],
    onPlay: null,
    passive: null,
    onDeath: null,
    text: "Brak zdolności.",
    copies: 2,
  },
  {
    id: "NEU-07",
    name: "Bot Swarm",
    type: "ACTION",
    faction: "NEUTRAL",
    cost: 3,
    atk: null,
    hp: null,
    rarity: "UNCOMMON",
    keywords: [],
    onPlay: {"op":"DAMAGE_ALL_ENEMIES_AT_NODE","amount":1},
    passive: null,
    onDeath: null,
    text: "Zadaj 1 obrażenie wszystkim wrogim jednostkom na wskazanym węźle.",
    copies: 2,
  },
  {
    id: "NEU-08",
    name: "Whale Wallet",
    type: "UNIT",
    faction: "NEUTRAL",
    cost: 4,
    atk: 4,
    hp: 4,
    rarity: "RARE",
    keywords: [],
    onPlay: null,
    passive: null,
    onDeath: null,
    text: "Brak zdolności.",
    copies: 2,
  },
  {
    id: "NEU-09",
    name: "Rug Insurance",
    type: "ACTION",
    faction: "NEUTRAL",
    cost: 2,
    atk: null,
    hp: null,
    rarity: "RARE",
    keywords: [],
    onPlay: {"op":"GRANT_SHIELD","target":"own_best_at_node"},
    passive: null,
    onDeath: null,
    text: "Wybrana własna jednostka na wskazanym węźle zyskuje Tarczę.",
    copies: 2,
  },
  {
    id: "NEU-10",
    name: "Community Vote",
    type: "ACTION",
    faction: "NEUTRAL",
    cost: 3,
    atk: null,
    hp: null,
    rarity: "RARE",
    keywords: [],
    onPlay: {"op":"DRAW","amount":2},
    passive: null,
    onDeath: null,
    text: "Dobierz 2 karty.",
    copies: 1,
  },
  {
    id: "NEU-11",
    name: "Cross-Chain Mercenary",
    type: "UNIT",
    faction: "NEUTRAL",
    cost: 5,
    atk: 5,
    hp: 5,
    rarity: "RARE",
    keywords: [],
    onPlay: null,
    passive: null,
    onDeath: null,
    text: "Brak zdolności.",
    copies: 1,
  },
  {
    id: "NEU-12",
    name: "The Anonymous Founder",
    type: "UNIT",
    faction: "NEUTRAL",
    cost: 6,
    atk: 4,
    hp: 6,
    rarity: "LEGENDARY",
    keywords: [],
    onPlay: {"op":"DRAW_AND_GAS","draw":2,"gas":2},
    passive: null,
    onDeath: null,
    text: "Po zagraniu: dobierz 2 karty i zyskaj 2 Gas w tej rundzie.",
    copies: 1,
  },
] as unknown as Card[];

export const CARDS_BY_ID: Record<string, Card> = Object.fromEntries(
  CARDS.map((c) => [c.id, c])
);

export const STARTER_DECK_IDS: Record<string, string[]> = {
  MINERS: ["MIN-01","MIN-01","MIN-02","MIN-02","MIN-03","MIN-03","MIN-04","MIN-04","MIN-05","MIN-05","MIN-06","MIN-06","MIN-07","MIN-07","MIN-08","MIN-08","MIN-09","MIN-10","MIN-11","MIN-12"],
  DEGENS: ["DEG-01","DEG-01","DEG-02","DEG-02","DEG-03","DEG-03","DEG-04","DEG-04","DEG-05","DEG-05","DEG-06","DEG-06","DEG-07","DEG-07","DEG-08","DEG-08","DEG-09","DEG-10","DEG-11","DEG-12"],
  BUILDERS: ["BLD-01","BLD-01","BLD-02","BLD-02","BLD-03","BLD-03","BLD-04","BLD-04","BLD-05","BLD-05","BLD-06","BLD-06","BLD-07","BLD-07","BLD-08","BLD-08","BLD-09","BLD-10","BLD-11","BLD-12"],
  VALIDATORS: ["VAL-01","VAL-01","VAL-02","VAL-02","VAL-03","VAL-03","VAL-04","VAL-04","VAL-05","VAL-05","VAL-06","VAL-06","VAL-07","VAL-07","VAL-08","VAL-08","VAL-09","VAL-10","VAL-11","VAL-12"],
};

export function getCard(id: string): Card {
  const c = CARDS_BY_ID[id];
  if (!c) throw new Error(`Unknown card id: ${id}`);
  return c;
}
